<?php
	require_once "./database.php";
    // Inclue the database connection
    //require_once "./scripts/includes/DBconnect.inc";
    require_once "./scripts/includes/functions.inc";
    session_start();
?>
<!DOCTYPE html>
<html>
    <head>
    	<meta name="viewport" content="width=device-width" />
    	<!-- Font Awesome Icons -->
		<link href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" rel="stylesheet">
		<!-- Style Sheet -->
		<link href="./css/design.css" rel="stylesheet" type="text/css"/>
		<script src="./scripts/starratingscript.js"></script>
		<script src="./scripts/individualresultscript.js"></script>
		<script src="./scripts/formvalidation.js"></script>
		<!--<script src="https://maps.google.com/maps/api/js?sensor=false"></script>-->
		<title>BNE Wi-Fi Reviews</title>
	</head>


